### ISSUE TITLE
SHA that appears on published pages does not exist in /wptd/testruns-index.json

### ISSUE THREAD

**Issue by rwaldron** [GoogleChrome/wptdashboard#104]
As show in: 

![](https://i.gyazo.com/a24facee8b675c6db60097403a0f390a.png)

This: `e511e5e8af` is not present in https://storage.googleapis.com/wptd/testruns-index.json

**Comment by jeffcarp** [comment]
Re: https://github.com/GoogleChrome/wptdashboard/issues/73#issuecomment-320740030, there's nothing that regularly updates the index yet.

**Comment by jeffcarp** [comment]
I just ran the script again so today's results should be in there. Until #73 is resolved, though, it won't be updated regularly.

**Comment by rwaldron** [comment]
Sorry, I should've closed it yesterday when I read that ticket—this is a duplicate
