### ISSUE TITLE
Add caveats to about text?

### ISSUE THREAD

**Issue by RByers** [GoogleChrome/wptdashboard#107]
Since web devs (and even tech press) may look at the dashboard, we might want to add some caveats about how not to interpret the results.  Eg:
- the test suite has inconsistent quality and coverage - many failures are test bugs
- pass rates are not scores.  A minor issue sometimes causes many test failures, while a major issue may cause only a single failure (or possibly none at all!)
- the suite and dashboard is designed to be useful to browser and standards engineers as part of our shared effort to make the web as a whole higher quality.

Thoughts?

**Comment by jgraham** [comment]
Agreed.

**Comment by foolip** [comment]
That would be great. I wouldn't mind making as prominent as a big red warning on first visit, or however far other would be comfortable going :)

**Comment by thejohnjansen** [comment]
Yeah, given the state of the tests, I'd think a big red warning would help. As we build confidence in the suite and the results posted, then things might change, but (for example) some tests are using non-standard ways of writing to the page (document.body.append()) which may cause tests to fail, even though the browser passes the actual test itself. Until we are able to really get this suite to the point of engineering confidence, I'm wary of giving it too much weight.

**Comment by jeffcarp** [comment]
IMHO I think a big red caveat on all pages is appropriate until items like #98 and what @thejohnjansen mentioned are resolved.

How does this sound as a caveat:

> Data is intended for web platform implementers and is not a reliable view of web platform features. Also note that tested Edge and Safari are not pre-release versions (link to bug).

(please re-mix as you see fit, I'll work on a PR)

**Comment by jeffcarp** [comment]
Uploaded a PR for this: #111 
And deployed the branch to https://caveat-dot-wptdashboard.appspot.com

**Comment by jeffcarp** [comment]
Landed: http://wpt.fyi/

PR's welcome if you think the wording should be different.

**Comment by RByers** [comment]
Looks great, thanks Jeff!
