### ISSUE TITLE
Support latest version of all browsers

### ISSUE THREAD

**Issue by jeffcarp** [GoogleChrome/wptdashboard#19]
The WPT Dashboard should work on the browsers whose results it displays. Ironically right now this dashboard, which is focused on web interoperability, is not interoperable.

Most of the modifications will need to be done in `components/`. Specifically:

- We can't use raw `async`/`await`

**Comment by gsnedders** [comment]
It doesn't work in Safari Technology Preview at the moment, though it does support `async`/`await`.
