### ISSUE TITLE
Set up DNS for results.web-platform-tests.org

### ISSUE THREAD

**Issue by jeffcarp** [GoogleChrome/wptdashboard#33]
@jgraham suggested we serve the site at results.web-platform-tests.org. He needs the DNS details in order to do that, and since the site runs on App Engine I believe an admin needs to set it up as a custom domain.

**Comment by jeffcarp** [comment]
@jgraham so in order to go through this process we'll need to set a CNAME record for domain verification:
https://cloud.google.com/appengine/docs/standard/python/using-custom-domains-and-ssl

If that sounds good, I'll start the verification process and can send you the correct CNAME over IRC.

**Comment by jgraham** [comment]
Ah, apologies for not replying here. This sounds good.

**Comment by jeffcarp** [comment]
It's up, thanks!

http://results.web-platform-tests.org
