### ISSUE TITLE
Store and show test failure messages

### ISSUE THREAD

**Issue by jeffcarp** [GoogleChrome/wptdashboard#53]
If a subtest fails, we should store that message and surface it in the dashboard. The results logs we generate already contain the message, we're just dropping it right now.

Work on this is dependent on #17 landing.

**Comment by davidsgrogan** [comment]
This would help diagnose why wpt.fyi shows some tests as failing even though they pass locally. E.g.
in http://wpt.fyi/css/css-tables-3, these tests are marked as failing in FF but they pass locally

http://w3c-test.org/css/css-tables-3/visibility-collapse-row-002-dynamic.html
http://w3c-test.org/css/css-tables-3/visibility-hidden-row-001.html
http://w3c-test.org/css/css-tables-3/visibility-hidden-row-002.html

**Comment by foolip** [comment]
This would have been very useful for me today. http://wpt.fyi/html/dom/interfaces.html fails in "Test driver" on Safari which means that something went wrong when trying to collect all the objects to test, or something. If I could see it in the web interface, I might be able to fix the test quickly.

It works in Safari 101.1 in BrowserStack though.

@bobholt FYI. Are you already getting notifications from everything in the repo so I don't need to poke you?

**Comment by foolip** [comment]
Looks like https://github.com/GoogleChrome/wptdashboard/pull/17 has been merged now, so maybe this is easy-ish now?

**Comment by bobholt** [comment]
@foolip. Yes, I'm watching this repo and getting all notifications. It probably doesn't hurt to poke me if you really need my attention, though, so I see my name when I'm scanning emails.

**Comment by jeffcarp** [comment]
We already store the whole raw object from `wptreport`, so theoretically we would already be storing failure messages.

However, looking at the log artifacts we get from wptrunner, `message` is always `null` even when there should be a string there. Example:

```json
{"message": null, "subtests": [{"message": null, "status": "FAIL", "name": "navigator.getBattery() shall throw a 'SecurityError' in an insecure context"}], "status": "OK", "test": "/battery-status/battery-insecure-context.html"}
```

It looks like in `tools/wptrunner/wptrunner/formatters.py`, failure messages for subtests are never applied. If I patch that class, we get the correct output:

```json
{"message": null, "subtests": [{"message": "assert_unreached: Should have rejected: undefined Reached unreachable code", "name": "navigator.getBattery() shall throw a 'SecurityError' in an insecure context", "status": "FAIL"}], "status": "OK", "test": "/battery-status/battery-insecure-context.html"}
```

I'll create a PR upstream to fix this issue. Once that lands, without any further effort we should start storing failure messages. Then the last step to fix this problem is to surface the messages in the UI (they will already be included in the result objects fetched on test file pages).

**Comment by jeffcarp** [comment]
> Then the last step to fix this problem is to surface the messages in the UI

I forgot that I had originally coded the UI in the first place expecting these messages, so now that https://github.com/w3c/web-platform-tests/pull/6854 has landed they're now being displayed: 
http://wpt.fyi/battery-status/battery-iframe.https.html

Currently Chrome and Firefox show messages because they're being run daily. Edge and Safari will show messages as well once they're run again.

**Comment by foolip** [comment]
Yay, thanks for getting that fixed, very helpful!
