### ISSUE TITLE
Documented dev_appserver start command doesn't work on linux

### ISSUE THREAD

**Issue by bobholt** [GoogleChrome/wptdashboard#75]
Out of the gcloud/appengine box on Linux, you have to include the `.py` extension.

```
dev_appserver.py .
```

Before I make a PR to change the README, I want to make sure that works on OSX/Windows (i.e. that they don't come with an extensionless shell script instead of a `.py` file).

**Comment by jeffcarp** [comment]
This was most likely just my mistake, I'll fix it.
