### ISSUE TITLE
Upgrade from Firefox 56 to 57

### ISSUE THREAD

**Issue by jeffcarp** [GoogleChrome/wptdashboard#85]
Firefox, running on `instance-4`, needs to be upgraded. I believe 57 is nightly now:
https://en.wikipedia.org/wiki/Firefox_version_history

**Comment by jeffcarp** [comment]
Getting a weird error after pulling down the latest FF nightly :confused: 

```
 0:06.49 PROCESS_OUTPUT: ProcessReader (pid:11444) "(firefox:11444): GConf-WARNING **: Client failed to connect to the D-BUS daemon:"
 0:06.49 PROCESS_OUTPUT: ProcessReader (pid:11444) "/usr/bin/dbus-launch terminated abnormally without any error message"
 0:06.54 PROCESS_OUTPUT: ProcessReader (pid:11444) "FATAL ERROR: Non-local network connections are disabled and a connection attempt to example.com (93.184.216.34) was made."
 0:06.54 PROCESS_OUTPUT: ProcessReader (pid:11444) "You should only access hostnames available via the test networking proxy (if running mochitests) or from a test-specific httpd.js server (if running xpcshell tests). Browser services should be disabled or redirected to a local server."
 0:06.54 PROCESS_OUTPUT: ProcessReader (pid:11444) "ExceptionHandler::GenerateDump cloned child 11526"
 0:06.54 PROCESS_OUTPUT: ProcessReader (pid:11444) "ExceptionHandler::SendContinueSignalToChild sent continue signal to child"
 0:06.54 PROCESS_OUTPUT: ProcessReader (pid:11444) "ExceptionHandler::WaitForContinueSignal waiting for continue signal..."
```

**Comment by jgraham** [comment]
Hmm, are you installing the gecko prefs that |wpt run| installs? Those are needed to avoid connecting to some random external services, which result in a crash in the test environment. Not sure what would be trying to connect to `example.com` though.

**Comment by jeffcarp** [comment]
@jgraham that was totally it. That VM is now upgraded.

cc @bobholt, I just took these actions:

- changed the crontab on `instance-4` from `firefox-56.0-linux` to `firefox-57.0-linux`
- pushed an update to `browsers.json` that adds that configuration: 36d7df0d89e459f1145af0685c1fa72a0b10477f
- started a manual run of FF 57 to verify everything works

Also, this was the last issue in this repo assigned to me - once I have a better idea of future workload I'm still interested in picking up issues as 20% time permits :smile_cat:
