### ISSUE TITLE
Lots of Webdriver Tests are not Run

### ISSUE THREAD

**Issue by JKereliuk** [GoogleChrome/wptdashboard#94]
Chrome runs a lot of webdriver tests, but firefox, edge and safari do not: [http://wpt.fyi/webdriver](http://wpt.fyi/webdriver)

**Comment by gsnedders** [comment]
Looks just like #90?

**Comment by jgraham** [comment]
Safari and Edge aren't yet supported for WebDriver tests. Adding support is pretty trivial but they are likely to ERROR on all tests until they fix basic conformance issues in their implementations (or I add hacks to make them work with tests that aren't specifically about the protocol).

**Comment by JKereliuk** [comment]
@gsnedders You are right, closing this as a duplicate

@jgraham That's true, but why isn't it running for geckodriver on firefox?
