### ISSUE TITLE
No results for server-timing/

### ISSUE THREAD

**Issue by foolip** [GoogleChrome/wptdashboard#96]
http://wpt.fyi/server-timing/ has no results, even though the tests were last updated 12 days ago:
https://github.com/w3c/web-platform-tests/commit/8fce5ee15419c99ba951c3bf9c11b4220815dc18

http://wpt.fyi/dom/ has much more recent results.

**Comment by bobholt** [comment]
Is this tied to https://github.com/GoogleChrome/wptdashboard/issues/105 or was it an intermittent bug? I currently see results at http://wpt.fyi/server-timing

**Comment by foolip** [comment]
Ah, it's just a dupe of https://github.com/GoogleChrome/wptdashboard/issues/105 then.
